# Generated by Django 4.0 on 2021-12-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Store name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Business name')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SlotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.SmallIntegerField(verbose_name='Slots')),
                ('activity', models.CharField(choices=[('P', 'Purchase'), ('S', 'Subscription')], max_length=2, verbose_name='Activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.seller', verbose_name='Reseller')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.supplier', verbose_name='Supplier')),
            ],
            options={
                'verbose_name_plural': 'Slot Allocations',
            },
        ),
    ]
