# Generated by Django 3.2a1 on 2021-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='slotallocation',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='slotallocation',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='SlotAllocation',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
