# Generated by Django 3.2a1 on 2022-01-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220105_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamplatform',
            options={'verbose_name_plural': 'Stream Platforms'},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name_plural': 'Watch Lists'},
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.CharField(max_length=150, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='streamplatform',
            name='website',
            field=models.CharField(max_length=100, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.CharField(max_length=200, verbose_name='Story Line'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
